#!/bin/bash
#SBATCH -J taweret_calibration_addstepasym_20000_exp_10
#SBATCH --partition=serial        # Queue (partition) name
#SBATCH --nodes=1                # the number of nodes
#SBATCH --ntasks-per-node=28
#SBATCH -t 24:00:00           # Run time (hh:mm:ss)   walltime for each node separately
#SBATCH --mail-user=liyanage.5@osu.edu
#SBATCH --mail-type=BEGIN,END      # Send email at begin and end of job
#SBATCH -A pas0254      # Allocation name
#COMMANDS TO RUN
#prepare environment
source ~/.bashrc
source set_variable.sh
#source ~/osc_prepare.sh
#cd to working dir
cd /users/PAS0254/dananjaya/Taweret/docs/source/notebooks
echo "in cwd"
pwd
#prepare the libraries
echo "preparing libraries"
#module load python/3.6-conda5.2
#conda activate parton_loss_owens
#conda activate random_field
#conda activate jstaw
conda env list
#inputdir=../input-config/ktiso/ #where the tables for iS3D, smash... are located. 
#echo "inputdir = "
#echo $inputdir
#echo "scratch = "
#echo ${SCRATCH}
job=$PBS_JOBID
#echo "job : "
#echo $job
echo "tmp dir"
echo ${TMPDIR}
#echo "Random field mean : "
#echo ${m}
#echo "randome field variance : "
#echo ${s}
#echo "random field correlation length : "
#echo ${l}

#n_cores=28
#let max_cores=$n_cores-1
#n_events_all=5000
#n_events_per_core=1
#echo "number of cores used : "
#echo ${n_cores}
##for best scaling, set nevents ?
#for j in $(seq 0 $n_events_all)
#do
#   srun -N1 -n1 --cpus-per-task=1 --exclusive python3 run-events-MAP-ALICE-osc-ktiso.py --m ${m} --s ${s} --l 1 --j ${j} --nevents ${n_events_per_core} --logfile ${SCRATCH}logs/$job/$j.log --tmpdir=$TMPDIR --tablesdir=$inputdir ${SCRATCH}results/$job/$j.dat &
#done
#wait until all processes are done
conda list|grep bilby
python3 calibration_jetscape_grad_ptb_addstepasym.py
wait
echo "All done. Goodbye!"
