name: Test oldest versions
env:
  CLONE_PATH: ${{ github.workspace }}
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Python version should be maintained consistent with value in pyproject.toml,
  # tox.ini, etc.
  #
  # Since the main test action is installing MPI implementations manually using
  # OS package managers, we have this action install MPI via PyPI/pip.
  tests:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-14, macos-15, macos-26, macos-26-intel]
        mpi_impl: ["openmpi", "mpich"]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      # TODO: Remove this once OpenBT is officially in it's new PyPI project
      # space.
      - name: Checkout OpenBT repository
        uses: actions/checkout@v6
        with:
          repository: bandframework/OpenBT
          path: ${{ env.CLONE_PATH }}/OpenBT
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup base Python environment
        run: $CLONE_PATH/.github/workflows/setup_base_python.sh ${{ runner.os }}
      - name: Install ${{ matrix.mpi_impl }}
        run: |
          if   [ "${{ matrix.mpi_impl }}" = "openmpi" ]; then
             python -m pip install openmpi
          elif [ "${{ matrix.mpi_impl }}" = "mpich" ]; then
             python -m pip install mpich
          else
             echo "Cannot install ${{ matrix.mpi_impl }}"
             exit 1
          fi
          python -m pip list
      - name: Run tests
        run: |
          which mpirun || echo "Cannot find the MPI installation"
          which mpicxx || echo "Cannot find the MPI compiler wrapper"
          mpicxx -show || echo "Cannot check the MPI wrapper specification"
          pushd $CLONE_PATH
          OPENBT_PATH=$CLONE_PATH/OpenBT tox -r -e oldest
          popd
